name = "brutalaf"
description = "A theme based on brutalist design"
license = "MIT"
homepage = "https://github.com/ranfdev/brutalaf"
min_version = "0.8.0"
demo = ""

[author]
name = "Lorenzo Miglietta"
homepage = "https://github.com/ranfdev"